In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
a=np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.size

3

In [8]:
a.shape

(3,)

In [9]:
a=np.array([[1,2,3],
            [2, 3, 4],
            [5, 6, 7]])

a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [10]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [14]:
a=np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a=np.random.random((3,3))
a

array([[0.50724336, 0.02465219, 0.28462757],
       [0.74336941, 0.64572081, 0.56369918],
       [0.26245334, 0.8545801 , 0.77167449]])

In [16]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [17]:
a+4

array([4, 5, 6, 7])

In [18]:
a*2

array([0, 2, 4, 6])

In [19]:
a/3

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [20]:
b=np.arange(4,8)
b

array([4, 5, 6, 7])

In [21]:
c=a-b
c

array([-4, -4, -4, -4])

In [22]:
print(b)
c=np.sin(b)
c

[4 5 6 7]


array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [23]:
a=np.arange(0,9).reshape(3,3)
b=np.ones((3,3))

print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
c=np.dot(a,b)
c

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [25]:
a=np.arange(0,9)
b=np.ones((3,3))

print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
a=np.sqrt(a)
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [27]:
l=np.log(a)
l

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.34657359, 0.54930614, 0.69314718,
       0.80471896, 0.89587973, 0.97295507, 1.03972077])

In [28]:
c=a.sum()
c

16.30600052603572

In [29]:
print("The array is :", a)
print("The sum : ", b)

The array is : [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712]
The sum :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
a=np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a.mean()

4.0

In [32]:
a.std()

2.581988897471611

In [33]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
print("The elements : ", a[1,2])


The elements :  5


In [35]:
print("The elements : ", a[::2])


The elements :  [[0 1 2]
 [6 7 8]]


In [36]:
print("The elements : ", a[:3:2])

The elements :  [[0 1 2]
 [6 7 8]]


In [37]:
print("The elements : ", a[:2:2])

The elements :  [[0 1 2]]
