**Name: Md. Anas Mondol**

**ID: 1935202011**

**Dept: CSE (Day)**

**Batch: 52nd-(A)**
**Gmail: mdanasmondol43@gmail.com**

**City University of Bangladesh**

In [1]:
#install numpy library if theere not available.

!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# import the NumPy module
import numpy as np

__Q1. Create a `3*3` matrix with random values?__

In [3]:
#random() function of the numpy it will provide random values which we need for works.

#argument row = 3, col = 3
matrix1=np.random.random((3,3))
matrix1

array([[0.77098784, 0.51694211, 0.9806971 ],
       [0.75407093, 0.9558665 , 0.41161824],
       [0.23609521, 0.84927044, 0.9905351 ]])

In [4]:
#we can create using integer number with randint() function

# 1st and 2nd argument numbers ranging from 10 to 20
# 3rd argument, row = 3, col = 3

matrix2=np.random.randint(10,20,size=(3,3))
matrix2

array([[18, 19, 18],
       [16, 19, 17],
       [14, 12, 17]])

__Q2. Find the values in the matrix of `Q1` which are greater than `0.5`?__

In [5]:
#operator condition will return boolean array which will show True and False.
#taken matrix1 from Q1 answer.

greater_than1=matrix1 > 0.5
greater_than1

array([[ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True]])

In [6]:
#another way which will provide numerical values.

greater_than2=matrix1[matrix1 > 0.5]
greater_than2

array([0.77098784, 0.51694211, 0.9806971 , 0.75407093, 0.9558665 ,
       0.84927044, 0.9905351 ])

__Q3. Convert this `2` dimensional matrix into `one` dimension array?__

In [7]:
#we can create using integer number with randint() function
# 1st argument numbers ranging up to 10
# 2nd argument, row = 3, col = 3

create_matrix=np.random.randint(10,size=(3,3))
create_matrix

array([[9, 5, 6],
       [8, 4, 2],
       [1, 1, 8]])

In [8]:
#ravel() function convert this 2D matrix into one dimension array. Also it is possible to do using reshape() functions.

convert_array=create_matrix.ravel()
convert_array

array([9, 5, 6, 8, 4, 2, 1, 1, 8])

__Q4. Create a `4*4` matrix `B` with random values and find its `Transpose`?__

In [9]:
#random() function of the numpy it will provide random values which we need to works.
#argument row = 4, col = 4

B=np.random.random((4,4))
B

array([[0.99994498, 0.95535208, 0.09519544, 0.92036565],
       [0.87652433, 0.09228306, 0.32943399, 0.87746289],
       [0.4780699 , 0.57804858, 0.13694316, 0.0752912 ],
       [0.68365204, 0.88562415, 0.96841856, 0.82534676]])

In [10]:
#transpose() function can be invert the columns with the rows.

transpose=B.transpose()
transpose

array([[0.99994498, 0.87652433, 0.4780699 , 0.68365204],
       [0.95535208, 0.09228306, 0.57804858, 0.88562415],
       [0.09519544, 0.32943399, 0.13694316, 0.96841856],
       [0.92036565, 0.87746289, 0.0752912 , 0.82534676]])

__Q5. Create a `4*4` matrix then convert it to `2*8` matrix ? [Horizontally and vertically]__

In [11]:
#we can create using integer number with randint() function
# 1st argument numbers ranging up to 10
# 2nd argument, row = 4, col = 4

convert_matrix=np.random.randint(10, size=(4,4))
convert_matrix

array([[5, 6, 0, 3],
       [1, 6, 1, 0],
       [2, 8, 6, 0],
       [2, 1, 5, 9]])

In [12]:
#reshape() function provide new shape to an array without changing its data.

re_convert=convert_matrix.reshape(2,8)
re_convert

array([[5, 6, 0, 3, 1, 6, 1, 0],
       [2, 8, 6, 0, 2, 1, 5, 9]])

In [13]:
#hstack() function performs horizontal stacking

horizontal=np.hstack(re_convert)
horizontal

array([5, 6, 0, 3, 1, 6, 1, 0, 2, 8, 6, 0, 2, 1, 5, 9])

In [14]:
#vstack() function can be perform vertical stacking

vertical=np.vstack(re_convert)
vertical

array([[5, 6, 0, 3, 1, 6, 1, 0],
       [2, 8, 6, 0, 2, 1, 5, 9]])

**Q6. Create a array of `8` items then copy this array to another variable?**

In [15]:
array=np.arange(8)
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
# copy() function helps to generate a complete and distinct array.

copy_array=array.copy()
copy_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
#If you want to change the items in array then copy_array will remains unchanged.
value_change=array[0]=1
value_change

1

In [18]:
array

array([1, 1, 2, 3, 4, 5, 6, 7])

In [19]:
#It has still unchanged.
copy_array

array([0, 1, 2, 3, 4, 5, 6, 7])

__Q7. Create a `csv` file which contains records set of student record.(Name, Department, admission, year) including atleast `10 records` with `columns name`. Read and show the file from Pythons using `Numpy` library?__

In [20]:
#Create a data frame using numpy array with columns name.

DataFrame=np.array([(1,"Md. Anas Mondol","CSE", 2019),(2,"Pranta Saha","CSE",2018),
                    (3,"Monjur Ahmed","CSE", 2018),(4,"Shakil Mahmud","CSE",2019),
                    (5,"M.N Huda Nahid","CSE", 2019),(6,"Dibos Saha","CSE",2019),
                    (7,"Md. Monir Hossain","CSE", 2019),(8,"Jahid Hasan","CSE",2019),
                    (9,"Md. Rayhan Khan","CSE", 2019),(10,"Nayem Hossain","CSE",2019)],
                   dtype=[('ID', 'i2'),('Name','a20'), ('Department','a4'), ('Admission Year','i4')])

DataFrame

array([( 1, b'Md. Anas Mondol', b'CSE', 2019),
       ( 2, b'Pranta Saha', b'CSE', 2018),
       ( 3, b'Monjur Ahmed', b'CSE', 2018),
       ( 4, b'Shakil Mahmud', b'CSE', 2019),
       ( 5, b'M.N Huda Nahid', b'CSE', 2019),
       ( 6, b'Dibos Saha', b'CSE', 2019),
       ( 7, b'Md. Monir Hossain', b'CSE', 2019),
       ( 8, b'Jahid Hasan', b'CSE', 2019),
       ( 9, b'Md. Rayhan Khan', b'CSE', 2019),
       (10, b'Nayem Hossain', b'CSE', 2019)],
      dtype=[('ID', '<i2'), ('Name', 'S20'), ('Department', 'S4'), ('Admission Year', '<i4')])

In [21]:
#Find names

DataFrame["Name"]

array([b'Md. Anas Mondol', b'Pranta Saha', b'Monjur Ahmed',
       b'Shakil Mahmud', b'M.N Huda Nahid', b'Dibos Saha',
       b'Md. Monir Hossain', b'Jahid Hasan', b'Md. Rayhan Khan',
       b'Nayem Hossain'], dtype='|S20')

In [22]:
#Find ID

DataFrame['ID']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

In [23]:
#Find Admission year

DataFrame["Admission Year"]

array([2019, 2018, 2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019],
      dtype=int32)

In [24]:
# use the tofile() method
# and use ',' as a separator
# as we have to generate a csv file

create_csv=DataFrame.tofile('Lab_Work_Numpy.csv', sep = ',')
create_csv

In [25]:
#Loading CSV data using numpy genfromtxt() method

load_data = np.genfromtxt('Lab_Work_Numpy.csv', delimiter=',', dtype=str)
load_data

array(['(1', " b'Md. Anas Mondol'", " b'CSE'", ' 2019)', '(2',
       " b'Pranta Saha'", " b'CSE'", ' 2018)', '(3', " b'Monjur Ahmed'",
       " b'CSE'", ' 2018)', '(4', " b'Shakil Mahmud'", " b'CSE'",
       ' 2019)', '(5', " b'M.N Huda Nahid'", " b'CSE'", ' 2019)', '(6',
       " b'Dibos Saha'", " b'CSE'", ' 2019)', '(7',
       " b'Md. Monir Hossain'", " b'CSE'", ' 2019)', '(8',
       " b'Jahid Hasan'", " b'CSE'", ' 2019)', '(9',
       " b'Md. Rayhan Khan'", " b'CSE'", ' 2019)', '(10',
       " b'Nayem Hossain'", " b'CSE'", ' 2019)'], dtype='<U21')

**Author**

***Md. Anas Mondol***, **City University.**