In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Create a numpy array Y

Y = np.array([[2,1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [4]:
# Multiply Y with 2

Z = 2*Y
Z

array([[4, 2],
       [2, 4]])

In [5]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [6]:
# Multiply X with Y

Z = X*Y
Z

array([[2, 0],
       [0, 2]])