In [8]:
import numpy as np
import pandas as pd

In [9]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [10]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [11]:

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [12]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)

In [13]:
Z

array([[2, 1],
       [1, 2]])

In [14]:
with open("Exampl1.txt","r") as File1:

    file_stuff=File1.readline ()

    print(file_stuff)

FileNotFoundError: [Errno 2] No such file or directory: 'Exampl1.txt'