In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [7]:
print(arr[0:6:3])

[1 4]


In [8]:
#If we don't pass start its considered 0

arr[:4]

array([1, 2, 3, 4])

In [9]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [10]:
#If we don't pass step its considered 1

arr[1:5:]

array([2, 3, 4, 5])

In [11]:
arr[0:6:]

array([1, 2, 3, 4, 5, 6])

In [13]:
#Print the even elements in the given array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr[1:8:2]

array([2, 4, 6, 8])

In [15]:
#Print the odd elements in the given array.

arr[0:7:2]

array([1, 3, 5, 7])