In [1]:
import numpy as np

In [2]:
# Create a numpy array

x = np.array([1, 2])
x

array([1, 2])

In [3]:
# Create a numpy array

y = np.array([2, 1])
y

array([2, 1])

In [4]:
# Numpy Array Multiplication

z = np.multiply(y, x)
z

array([2, 2])

In [5]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

# Enter your code here
arr3 = np.multiply(arr1, arr2)
arr3

array([ 20,  20,  60, 120, 200, 300])

In [7]:
#Array Division

a= np.array([10, 20, 30])
a

array([10, 20, 30])

In [8]:
b = np.array([2, 10, 5])
b

array([ 2, 10,  5])

In [9]:
#We can divide the two arrays and assign it to c:

c = np.divide(a, b)
c

array([5., 2., 6.])

In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

# Enter your code here

arr3 = np.divide(arr1,arr2)
arr3

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])