In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [9]:
# Create a numpy array Y

Y = np.array([[2,1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [11]:
# Add X and Y

Z = X+Y
Z

array([[3, 1],
       [1, 3]])