In [1]:
import numpy as np

In [2]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [5]:
# Calculate the dot product
Z = np.dot(X, Y)
Z

7

In [6]:
#Elements of X
print(X[0])
print(X[1])

1
2


In [7]:
#Elements of Y
print(Y[0])
print(Y[1])

3
2


In [8]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])

# Enter your code here
arr3 = np.dot(arr1, arr2)
arr3

26

In [9]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

In [11]:
# Add the constant to array

u + 1

array([2, 3, 4, 0])

In [12]:
#Add Constant 5 to the given numpy array ar:

arr = np.array([1, 2, 3, -1]) 

# Enter your code here
arr+5

array([6, 7, 8, 4])

In [13]:
#We can access the value of pi in numpy as follows :

np.pi

3.141592653589793

In [15]:
# Create the numpy array in radians

x = np.array([0, np.pi/2, np.pi])
x

array([0.        , 1.57079633, 3.14159265])

In [16]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])