In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Consider the following list a, convert it to Numpy Array

import numpy as np
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

b = np.array(a)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
#Calculate the numpy array size.

b.size

12

In [4]:
#Access the element on the first row and first and second columns.

b[0][0:2]

array([1, 2])

In [5]:
#Perform matrix multiplication with the numpy arrays A and B

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [6]:
x = np.dot(a, B)
x

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])