In [3]:
# Create numpy array

import numpy as np

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [4]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [5]:
c[4] = 90
c

array([100,   1,   2,   3,  90])

In [6]:
#Assign the value 20 for the second element in the given array.

a = np.array([10, 2, 30, 40,50])

# Enter your code here
a[1]= 20
a

array([10, 20, 30, 40, 50])

In [7]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [8]:
d = c[0:3]
d

array([100,   1,   2])

In [9]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])