In [1]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
# Access the element on the second row and third column

A[1, 2]


23

In [9]:
A[2, 0]

31

In [11]:
A[2, 2]

33

In [12]:
# Access the element on the second row and third column

A[1][2]

23

In [13]:
# Access the element on the first row and first column

A[0][0]

11

In [14]:
A[0, 0]

11

In [15]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [16]:
A[0, 0:2]

array([11, 12])

In [18]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])