In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [3]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [4]:
# Calculate the dot product

Z = np.dot(A, B)
Z

array([[0, 2],
       [0, 2]])

In [5]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [6]:
#We use the numpy attribute T to calculate the transposed matrix

# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [7]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])