In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [3]:
b = np.array([5, 10, 15])
b

array([ 5, 10, 15])

In [4]:
#We can subtract the two arrays and assign it to c:

c = np.subtract(a, b)
c

array([ 5, 10, 15])

In [9]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

In [10]:
arr3 = np.subtract(arr1, arr2)
arr3

array([-10,  -1,   8,  17,  26,  35])